POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test blog",
  "author": "sz",
  "url": "fullstackopen.com",
  "likes": 12
}


###
GET http://localhost:3003/api/blogs